# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='enter_city',
        ),
        migrations.AlterField(
            model_name='loan',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=3, max_length=10),
            preserve_default=False,
        ),
    ]
