# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20191118_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
    ]
