# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20191118_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='select_state',
            field=models.CharField(blank=True, choices=[('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('Andhra', 'Andhra'), ('Telangana', 'Telangana')], max_length=10),
        ),
    ]
