# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_loan_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='monthly_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='salary_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transor', 'Bank Transor'), ('Cheque', 'Cheque')], max_length=10),
        ),
    ]
