# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20191118_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='monthly_salary',
            field=models.IntegerField(default=''),
        ),
    ]
