# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20191118_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='upload_bankstatement',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf/'),
        ),
    ]
