# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_loan_upload_bankstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Salaried', 'Salaried'), ('Self', 'SelfEmployed')], max_length=10),
        ),
    ]
