# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20191118_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Salaried', 'Salaried'), ('Self', 'Self')], max_length=10),
        ),
    ]
