# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_loan_upload_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='upload_pan',
            field=models.FileField(blank=True, null=True, upload_to='media/pan/'),
        ),
    ]
