# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_loan_upload_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='upload_bankstatement',
            field=models.FileField(blank=True, help_text='WITH SUB CASTE', null=True, upload_to='media/pdf/'),
        ),
    ]
